### ISSUE TITLE
Failed to load the language-sketchplugin package

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [daneden/language-sketchplugin#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [language-sketchplugin](https://github.com/daneden/language-sketchplugin) package, v0.3.0
### Stack Trace

Failed to load the language-sketchplugin package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/ashrafali/.atom/packages/language-sketchplugin/lib/language-sketchplugin-view.coffee:1:1)
  at /Users/ashrafali/.atom/packages/language-sketchplugin/lib/language-sketchplugin-view.coffee:5:3
  at Object.<anonymous> (/Users/ashrafali/.atom/packages/language-sketchplugin/lib/language-sketchplugin-view.coffee:52:5)
  at Object.<anonymous> (/Users/ashrafali/.atom/packages/language-sketchplugin/lib/language-sketchplugin-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/ashrafali/.atom/packages/language-sketchplugin/lib/language-sketchplugin.coffee:1:28)
  at Object.<anonymous> (/Users/ashrafali/.atom/packages/language-sketchplugin/lib/language-sketchplugin.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:725:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:176:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:473:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```
### Commands

```
     -2:05.7.0 grammar-selector:show (atom-text-editor.editor)
  3x -2:02.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:58 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:48.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:47.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:29.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
 12x -0:29.4.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  6x -0:26.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:25.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "minimap",
      "seti-icons",
      "close-on-left",
      "auto-indent",
      "indent-guide-improved",
      "multi-cursor",
      "linter-ruby",
      "ruby-debugger",
      "linter-phpcs",
      "tree-view",
      "linter-phpmd"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
aligner, v0.17.1
aligner-css, v1.2.0
aligner-php, v1.0.0
aligner-ruby, v1.4.0
aligner-scss, v1.1.0
angularjs, v0.3.3
atom-autocomplete-php, v0.18.1
atom-commander, v0.5.0
atom-html-preview, v0.1.13
auto-detect-indentation, v0.4.2
autocomplete-php, v0.3.7
autocomplete-ruby, v0.1.0
color-picker, v2.0.13
cucumber, v0.5.0
editorconfig, v1.2.2
file-icons, v1.6.11
git-log, v0.4.1
hashrocket, v0.4.8
highlight-selected, v0.10.1
imdone-atom, v1.1.53
language-blade, v0.16.0
language-gherkin, v1.0.3
language-sketchplugin, v0.3.0
laravel, v0.7.0
linter, v1.10.0
linter-clang, v3.3.0
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
linter-js-yaml, v1.2.0
linter-jshint, v1.2.1
linter-less, v2.2.0
linter-scss-lint, v2.4.0
linter-tidy, v1.0.1
mac-fix-path, v0.0.0
markdown-table-formatter, v2.5.4
monokai, v0.18.0
nucleus-dark-ui, v0.6.8
php-cs-fixer, v2.5.1
php-debug, v0.1.3
project-manager, v2.6.5
react, v0.12.10
sync-settings, v0.6.0
tree-view-breadcrumb, v0.8.0
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by shemerey** [comment]
same for me

**Comment by yaofan** [comment]
me too!

**Comment by yaofan** [comment]
but it works for me

**Comment by plrthink** [comment]
You could config atom to let it apply the color scheme comes with `language-javascript` to cocoascript as a workaround.

Add this

``` cson
"source.js": [
    "cocoascript"
]
```

to your atom's config.cson.

**Comment by agisilaos** [comment]
Any updates on that one @daneden? I tried to install this package today and I get that error:

### [Enter steps to reproduce:]

1. Install the plugin manually
2. restart atom

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [language-sketchplugin](https://github.com/daneden/language-sketchplugin) package 0.3.0


### Stack Trace

Failed to load the language-sketchplugin package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (/packages/language-sketchplugin/lib/language-sketchplugin-view.coffee:1:1)
    at /packages/language-sketchplugin/lib/language-sketchplugin-view.coffee:4:7
    at /packages/language-sketchplugin/lib/language-sketchplugin-view.coffee:19:11)
    at /packages/language-sketchplugin/lib/language-sketchplugin-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/language-sketchplugin/lib/language-sketchplugin.coffee:1:28)
    at /packages/language-sketchplugin/lib/language-sketchplugin.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:792:28
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-swift 1.0.3 
kite 0.22.0 
language-prolog 0.10.0 
language-sketchplugin 0.3.0 
language-swift 0.5.0 
nuclide 0.221.0 
swift-debugger 0.1.2 
toothpaste 1.0.0 
```

**Comment by seandellis** [comment]
@agisilaos Understandably it's a little confusing. I had the same problem and wrote this up for the next person that runs into it.

1. Go to the menu and select Atom → Config…

    It will open up config.cson. This is where Atom stores some of its settings.

2. Look for the line that starts with **core:**

3. Add a return under **core:** and paste this in.

    ```
    customFileTypes:
    	"source.js": [
    		"cocoascript"
    		"sketchscript"
    	]
    ```

    After pasting, make sure the lines are indented like the screenshot below. If you don't you may get an error message and it won't work.

    ![sketch-config cson](https://cloud.githubusercontent.com/assets/1584916/26162294/f671bf8c-3aeb-11e7-8169-6b62b78c926e.png)

4. Save config.cson and restart Atom.

    The next time you open a .sketchscript or .cocoascript file they should now use be color coded with Javascript syntax.
